import { ROLES } from "../utils/constants";

export const demoUsers = [
  {
    id: "u-admin",
    name: "Workspace Admin",
    email: "admin@taskmanagement.local",
    role: ROLES.ADMIN,
    jobTitle: "Workspace Administrator",
    department: "Operations",
    timezone: "Asia/Katmandu",
    active: true,
    teamIds: ["t-core"],
  },
];

export const demoProjects = [
  {
    id: "p-ops",
    name: "Client Operations Hub",
    key: "COH",
    description: "Centralize client onboarding, approvals, weekly delivery, and escalation tracking.",
    status: "Active",
    priority: "High",
    ownerId: "u-pm",
    teamIds: ["t-core"],
    startDate: "2026-06-01",
    dueDate: "2026-07-12",
    budget: 42000,
    color: "#2563eb",
    progress: 68,
  },
  {
    id: "p-mobile",
    name: "Mobile Task Companion",
    key: "MTC",
    description: "Fast personal task capture, daily focus view, and push notifications for field teams.",
    status: "Planning",
    priority: "Medium",
    ownerId: "u-admin",
    teamIds: ["t-core"],
    startDate: "2026-06-18",
    dueDate: "2026-08-01",
    budget: 28000,
    color: "#059669",
    progress: 32,
  },
  {
    id: "p-analytics",
    name: "Executive Reporting",
    key: "EXR",
    description: "Portfolio health, team utilization, overdue risk, and delivery confidence reports.",
    status: "Active",
    priority: "Critical",
    ownerId: "u-pm",
    teamIds: ["t-data"],
    startDate: "2026-05-20",
    dueDate: "2026-07-05",
    budget: 36000,
    color: "#dc2626",
    progress: 81,
  },
];

export const demoTeams = [
  {
    id: "t-core",
    name: "Core Delivery",
    description: "Product, engineering, and QA team responsible for day-to-day project delivery.",
    leaderId: "u-pm",
    memberIds: ["u-admin", "u-pm", "u-dev", "u-qa"],
    status: "Active",
  },
  {
    id: "t-data",
    name: "Reporting Guild",
    description: "Analytics and audit specialists focused on executive reporting accuracy.",
    leaderId: "u-admin",
    memberIds: ["u-admin", "u-pm", "u-qa"],
    status: "Active",
  },
];

export const demoTasks = [
  {
    id: "task-101",
    key: "COH-101",
    title: "Finalize onboarding checklist workflow",
    description: "Create the approval path for new client launch tasks and required handoffs.",
    projectId: "p-ops",
    assigneeId: "u-dev",
    reporterId: "u-pm",
    status: "In Progress",
    priority: "High",
    type: "Story",
    dueDate: "2026-07-02",
    storyPoints: 8,
    labels: ["workflow", "client"],
    comments: 4,
    attachments: 2,
  },
  {
    id: "task-102",
    key: "COH-102",
    title: "Review overdue-task escalation rules",
    projectId: "p-ops",
    assigneeId: "u-admin",
    reporterId: "u-pm",
    status: "In Review",
    priority: "Critical",
    type: "Task",
    dueDate: "2026-06-30",
    storyPoints: 5,
    labels: ["risk", "ops"],
    comments: 2,
    attachments: 1,
  },
  {
    id: "task-103",
    key: "COH-103",
    title: "Build stakeholder weekly summary template",
    projectId: "p-ops",
    assigneeId: "u-qa",
    reporterId: "u-admin",
    status: "To Do",
    priority: "Medium",
    type: "Task",
    dueDate: "2026-07-04",
    storyPoints: 3,
    labels: ["reporting"],
    comments: 1,
    attachments: 0,
  },
  {
    id: "task-201",
    key: "MTC-201",
    title: "Prototype quick-add task interaction",
    projectId: "p-mobile",
    assigneeId: "u-dev",
    reporterId: "u-pm",
    status: "Backlog",
    priority: "Medium",
    type: "Story",
    dueDate: "2026-07-11",
    storyPoints: 5,
    labels: ["mobile", "ux"],
    comments: 3,
    attachments: 1,
  },
  {
    id: "task-301",
    key: "EXR-301",
    title: "Validate portfolio health calculations",
    projectId: "p-analytics",
    assigneeId: "u-qa",
    reporterId: "u-admin",
    status: "Done",
    priority: "High",
    type: "Bug",
    dueDate: "2026-06-25",
    storyPoints: 8,
    labels: ["analytics", "quality"],
    comments: 6,
    attachments: 3,
  },
  {
    id: "task-302",
    key: "EXR-302",
    title: "Connect report export audit events",
    projectId: "p-analytics",
    assigneeId: "u-pm",
    reporterId: "u-admin",
    status: "In Progress",
    priority: "Critical",
    type: "Task",
    dueDate: "2026-07-01",
    storyPoints: 5,
    labels: ["audit", "reports"],
    comments: 2,
    attachments: 0,
  },
];

export const demoActivities = [
  { id: "a1", message: "Maya moved COH-102 into review", createdAt: "2026-06-28T09:15:00.000Z" },
  { id: "a2", message: "Aarav updated the onboarding workflow estimate", createdAt: "2026-06-28T08:40:00.000Z" },
  { id: "a3", message: "Nisha completed portfolio health validation", createdAt: "2026-06-27T16:20:00.000Z" },
  { id: "a4", message: "Workspace Admin approved executive reporting scope", createdAt: "2026-06-27T11:05:00.000Z" },
];

export const demoNotifications = [
  { id: "n1", message: "COH-102 is ready for final review", read: false, type: "review" },
  { id: "n2", message: "Executive Reporting is due next week", read: false, type: "deadline" },
  { id: "n3", message: "A new weekly summary task was assigned", read: true, type: "assignment" },
];

export function demoLogin(credentials = {}) {
  const user = demoUsers.find((item) => item.email === credentials.email) || demoUsers[0];
  return {
    token: "demo-workspace-token",
    user,
  };
}
